/**
 * Transpile Command
 *
 * Handles the 'transpile' CLI command for converting Pine Script to JavaScript.
 */

import { ASTGenerator } from '../../generator/ast-generator.js';
import { MetadataVisitor } from '../../generator/metadata-visitor.js';
import {
  generateStandaloneFactory,
  transpile,
  transpileToPineJS,
} from '../../index.js';
import { Lexer, Parser } from '../../parser/index.js';
import type { CLIOptions } from '../types';
import { deriveIndicatorId, readInput, writeOutput } from '../utils';

/**
 * Generate PineJS factory code for module export
 */
function generatePineJSFactoryCode(
  pineCode: string,
  indicatorId: string,
  indicatorName?: string,
): string {
  const escapedCode = JSON.stringify(pineCode);
  const nameStr = indicatorName ? JSON.stringify(indicatorName) : 'undefined';

  return `/**
 * PineJS Indicator Factory
 * Generated by pine-transpiler
 *
 * Usage:
 *   import { createIndicator } from './output.js';
 *   const indicator = createIndicator(PineJS);
 */

import { transpileToPineJS } from '@opusaether/pine-transpiler';

const pineCode = ${escapedCode};
const indicatorId = ${JSON.stringify(indicatorId)};
const indicatorName = ${nameStr};

export function createIndicator(PineJS) {
  const result = transpileToPineJS(pineCode, indicatorId, indicatorName);
  if (!result.success) {
    throw new Error('Transpilation failed: ' + result.error);
  }
  return result.indicatorFactory(PineJS);
}

export default createIndicator;
`;
}

/**
 * Execute the transpile command
 */
export function commandTranspile(
  file: string | undefined,
  options: CLIOptions,
): void {
  if (!file) {
    console.error('Error: No input file specified');
    console.error('Usage: pine-transpiler transpile <file>');
    process.exit(1);
  }

  const code = readInput(file);
  const format = options.format || 'js';

  if (format === 'js') {
    try {
      const result = transpile(code);
      writeOutput(result, options.output);
    } catch (error) {
      console.error(
        'Transpilation error:',
        error instanceof Error ? error.message : error,
      );
      process.exit(1);
    }
  } else if (format === 'pinejs') {
    const indicatorId = options.id || deriveIndicatorId(file);
    const indicatorName = options.name;

    const result = transpileToPineJS(code, indicatorId, indicatorName);

    if (!result.success) {
      console.error('Transpilation error:', result.error);
      process.exit(1);
    }

    const factoryCode = generatePineJSFactoryCode(
      code,
      indicatorId,
      indicatorName,
    );
    writeOutput(factoryCode, options.output);
  } else if (format === 'factory') {
    // Generate standalone factory code that can be directly pasted
    const indicatorId = options.id || deriveIndicatorId(file);
    const indicatorName = options.name;

    try {
      // Parse the Pine Script
      const lexer = new Lexer(code);
      const tokens = lexer.tokenize();
      const parser = new Parser(tokens);
      const ast = parser.parse();

      // Extract metadata
      const visitor = new MetadataVisitor();
      visitor.visit(ast);

      // Generate code
      const generator = new ASTGenerator(visitor.historicalAccess);
      const mainBody = generator.generate(ast);

      // Generate standalone factory
      const factoryCode = generateStandaloneFactory({
        indicatorId,
        indicatorName,
        name: visitor.name,
        shortName: visitor.shortName,
        overlay: visitor.overlay,
        plots: visitor.plots,
        inputs: visitor.inputs,
        bgcolors: visitor.bgcolors,
        usedSources: visitor.usedSources,
        historicalAccess: visitor.historicalAccess,
        mainBody,
        sessionVariables: visitor.sessionVariables,
        derivedSessionVariables: visitor.derivedSessionVariables,
        booleanInputMap: visitor.booleanInputMap,
        computedVariables: visitor.computedVariables,
        inputVariableMap: visitor.inputVariableMap,
      });

      writeOutput(factoryCode, options.output);
    } catch (error) {
      console.error(
        'Transpilation error:',
        error instanceof Error ? error.message : error,
      );
      process.exit(1);
    }
  } else {
    console.error(
      `Error: Unknown format '${format}'. Use 'js', 'pinejs', or 'factory'.`,
    );
    process.exit(1);
  }
}
